version: '3.8'

services:
  breachpilot:
    build: .
    container_name: breachpilot
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SHODAN_API_KEY=${SHODAN_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - breachpilot-network

networks:
  breachpilot-network:
    driver: bridge
