version: '3.8'

services:
  pentestpilot:
    build: .
    container_name: pentestpilot
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SHODAN_API_KEY=${SHODAN_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - pentestpilot-network

networks:
  pentestpilot-network:
    driver: bridge
